#!/bin/sh

if [ $# == 0 ]; then mpc playlist && exit; fi

if [ $1 == '-a' ]; then
	shift;
else
	mpc clear --quiet;
fi


# For some reason, "any" does not include "filename". Due to this, it requires all the following stuff to make mpc a first-class music searcher
for arg in "$@"
do
	anyQuery="$anyQuery any $arg"
	fileQuery="$fileQuery filename $arg"
done

IFS=$'\n'
tracks=`sh -c "mpc search $anyQuery"`"
"`sh -c "mpc search $fileQuery"`

tracks=`echo "$tracks" | sort -u | gsort -r`

for i in ${tracks}; do
	echo $i
	mpc add $i
done

mpc shuffle --quiet
mpc play --quiet
